language: java
sudo: required

dist: trusty

matrix:
  include:
    - os: linux
      jdk: openjdk11
      before_install:
        - chmod +x ./gradlew
        - sudo apt-get install libreoffice
      script:
        - ./gradlew clean build
        - ./gradlew integrationTest
#        - ./gradlew e2eTest
      after_success:
        - ./gradlew coveralls
