server:
  port: 8100
  
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  application:
    name: PdfConverter Rest Api

jodconverter:
  local:
    enabled: true
    port-numbers: 2002
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages

logging:
  level:
    org.jodconverter: info
